name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1

    - name: Build
      run: .\build.cmd

    - name: Test
      run: .\test.cmd

    - name: Save package artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: package
        path: artifacts

  linux_test:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    
    - name: Retrieve package built on Windows
      uses: actions/download-artifact@v1.0.0
      with:
        name: package
        path: artifacts

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1

    - name: Test
      run: dotnet build tests
